apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2024-11-14T14:34:21Z"
  labels:
    kubernetes.io/metadata.name: banreserva-web
  name: banreserva-web
  resourceVersion: "6148"
  uid: 5ccd2390-8990-46d2-955e-e99f73af370a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
