apiVersion: v1
kind: Service
metadata:
  name: web-page-service
  namespace: banreserva-web
spec:
  selector:
    app: web_page
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80

