stages:
  - plan
  - apply

variables:
  TF_WORKSPACE: "devops-HCP" # Nombre del workspace de Terraform Cloud

before_script:
  - apk add --no-cache curl bash jq
  - curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
  - export PATH=$PATH:/usr/local/bin

# Stage para ejecutar `terraform plan`
plan:
  stage: plan
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - main

# Stage para ejecutar `terraform apply`
apply:
  stage: apply
  image: hashicorp/terraform:latest
  dependencies:
    - plan
  script:
    - terraform apply -input=false "tfplan"
  when: manual
  only:
    - main
