stages:
  - deploy

before_script:
  - apk add --no-cache curl bash jq
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az --version
  - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
  - az aks get-credentials --resource-group "[rg_name]" --name "[cluster_name]]" --file kubeconfig

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - kubectl apply -f kubernetes/namespace.yaml
    - kubectl apply -f kubernetes/deploy-ingress-nginx.yaml
    - kubectl apply -f kubernetes/svc_loadbalancer.yaml
    - kubectl apply -f kubernetes/web_deployment.yaml
  only:
    - main
