apiVersion: v1
kind: Service
metadata:
  name: web-page-service
  namespace: redux-web
spec:
  selector:
    app: web_page
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          ## Service port
      targetPort: 80 ## Pod port

