name: Docker Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Enviroments/dev/docker/**'
      - 'Enviroments/dev/kubernetes/**'

jobs:
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Enviroments/dev/docker
          file: ./Enviroments/dev/docker/Dockerfile.yaml
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/api-hola-mundo:latest

  deploy-docker-to-aks:
    name: Deploy Docker Image to AKS
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v2

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az aks get-credentials --resource-group aks-dev --name aks-dev-cluster

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./Enviroments/dev/kubernetes/namespace.yaml
          kubectl apply -f ./Enviroments/dev/kubernetes/svc_loadbalancer.yaml
          kubectl set image deployment/web-deployment web-page=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/api-hola-mundo:latest
