name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: "devops-HCP" # Name of the Terraform Cloud workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
          export PATH=$PATH:/usr/local/bin
      - name: Initialize Terraform
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        id: plan
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
          export PATH=$PATH:/usr/local/bin
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        if: success()
