name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: "devops-HCP" # Name of the Terraform Cloud workspace
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
          mkdir -p $HOME/bin
          mv tfswitch $HOME/bin/
          export PATH=$PATH:$HOME/bin
      
      - name: Initialize Terraform
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        id: plan
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        if: success()
